orvice/ss-panel

- css/google-font.css
- lib/func/comm.func.php
> 更换部分由于墙所导致的水土不服

- lib/class/node.class.php
- user/code.php
> random invitation code

- admin/index.php
- admin/lib/slidebar_left.inc.php
- admin/user.php
- admin/user_check.php
- admin/user_del.php
- admin/user_edit.php
- lib/class/ss.class.php
- lib/class/user.class.php
> Update User Management

- admin/user_check.php
- user/user_check.php
> 修复当cookie的值为空的时候不跳转登陆界面的问题

- robots.txt
To protect the privacy,prevent spider to fetch config.php.
> to protect the privacy

- admin/my.php
- user/my.php
fixed “user name” in “my profile” page cannot be displayed BUG.
> fixed 'user name' in my.php cannot be displayed BUG.

- lib/Ss/mail-smtp.php
- lib/config-simple.php
- lib/test-mail-smtp.php
- user/_resetpwd.php
- user/_resetpwdtwo.php
Add mail smtp
支持发送纯文本邮件和HTML格式的邮件，可以多收件人，多抄送，多秘密抄送，带附件(单个或多个附件),支持到服务器的ssl连接
需要的php扩展：sockets、Fileinfo和openssl。
编码格式是UTF-8，传输编码格式是base64
> Add mail smtp

- admin/_footer.php
- user/_footer.php
fixed jquery.slimscroll.min.js cannot be loaded issues.
> fixed slimscroll cannot be loaded issues

- admin/login.php
- user/login.php
- user/register.php
- user/resetpwd.php
- user/resetpwd_do.php
修复关闭提示关闭之后，不能再次显示，现在可以再次显示。
把提示移至按钮下方，
提示再也不会影响-登录-注册-重置密码的操作！
支持按回车键登录-注册-重置密码。
修复按键自动提交问题(这是我之前版本的问题)。
> 优化 登录 注册 重置密码 页面

- admin/_user_edit.php
- admin/user_edit.php
- lib/Ss/User/User.php
一直不习惯没办法管理用户，所以今天自己尝试了修改，拿旧版的来对比，然而复制了一些代码，采用ajax+json提交，再也不用忍受那个alert弹窗了。添加设置邀请码
> 完善 编辑用户 添加设置邀请码

- views/default/user/nodeinfo.tpl
> nodeinfo.tpl: Use `render:"table"` for jquery.qrcode.js

- app/Controllers/UserController.php
- views/default/admin/main.tpl
- views/default/user/main.tpl
> fix parameter name in updating password

- app/Controllers/UserController.php
- public/assets/public/css/AdminLTE.min.css
- resources/views/default/user/node.tpl
- resources/views/default/user/nodeinfo.tpl
Change some UI in node list:
change:  some UI in node list
change:  some UI in node list detail. Now the JSON config can be in multiline and the URL can be easily select.
change: Remove Google fonts in CSS file. fix #338 
Sorry about indenting... My IDE auto-formated that...sorry.
> Chnage Some UI

- resources/views/default/admin/user/edit.tpl
1. It is "Byte" but "KB" in "Total Transfer" and "Used Transfer"
2. Now the "Used Transfer" can show the right number.
> Fix 2 bugs in Admin/User/UserEdit

- resources/views/default/user/node.tpl
Fix #359  
Maybe this's is a good way to fix this, without editing original CSS file.
Font size changes a little smaller, but it's okay.
> fix the password display problem in user interface

- README.md
base on -> based on.
Because it matters.
> Fixed English syntax error

- app/Models/User.php
transfer_enable 类型错误，应该使用BIGINT，签到添加流量会导致错误
> fix transfer_enable type error

- app/Models/User.php
> Revert "fix transfer_enable type error"

- .gitignore
- resources/views/default/admin/user/edit.tpl
> Fix User Edit.tpl type cass->class

- .gitignore
- app/Controllers/AdminController.php
- resources/views/default/admin/config.tpl
> Add User Node to Config Page

- resources/views/default/admin/user/edit.tpl
> fixed usedTraffic

- resources/views/default/user/edit.tpl
> SS连接信息修改处按钮位置修复

- app/Controllers/Admin/NodeController.php
- app/Controllers/Admin/UserController.php
- app/Controllers/Mu/UserController.php
- app/Controllers/UserController.php
- app/Models/CheckInLog.php
- app/Models/Node.php
- app/Models/TrafficLog.php
- app/Utils/Tools.php
- db.sql
- resources/views/default/admin/checkinlog.tpl
- resources/views/default/admin/index.tpl
- resources/views/default/admin/node/create.tpl
- resources/views/default/admin/node/edit.tpl
- resources/views/default/admin/trafficlog.tpl
- resources/views/default/admin/user/edit.tpl
- resources/views/default/user/edit.tpl
把加密方式设为下拉菜单
修改sql中user的reg_date定义
修改默认password的字符串，去掉了容易混淆的oO0和lI1，方便手工输入密码
修改了部分显示问题
> 加密方式设为下拉菜单等

- app/Models/User.php
According to this issue,
https://github.com/fsgmhoward/shadowsocks-py-mu/issues/25
> update user model to be compatible with py mu

- app/Controllers/AdminController.php
- app/Controllers/UserController.php
- app/routes.php
- resources/views/default/admin/trafficlog.tpl
- resources/views/default/user/trafficlog.tpl
admin和user的traffic log的筛选功能，user可筛选节点，admin可同时筛选节点和/或用户
> 用户和管理的Traffic Log界面增加筛选功能

- app/Controllers/AdminController.php
- resources/views/default/admin/sys.tpl
Replace the "alert" prompt on  submit of the sysinfo page with a common used alert area.
> Improve Sysinfo Front-end

- src/pages/Admin/Invite.vue
- src/pages/Admin/InviteAdd.vue
- src/pages/Admin/Node.vue
- src/pages/Admin/NodeAdd.vue
- src/pages/Admin/TrafficLog.vue
- src/pages/Admin/User.vue
- src/pages/Blank.vue
- src/pages/Invite.vue
- src/pages/Node.vue
- src/pages/Profile.vue
- src/pages/TrafficLog.vue
> Correct card width under extra large view (equal or above 1600px).
